### service-bot sonarqube plugin managed file
sonar.coverage.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.cpd.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.exclusions=**/*.py,**/*.pb.*,**/mk-include/**/*
sonar.language=java
sonar.projectKey=common-docker
sonar.sources=.
sonar.java.binaries=.
sonar.coverage.jacoco.xmlReportPaths=**/jacoco.xml
