### service-bot sonarqube plugin managed file
sonar.coverage.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.cpd.exclusions=**/test/**/*,**/tests/**/*,**/mock/**/*,**/mocks/**/*,**/*mock*,**/*test*
sonar.exclusions=**/*.py,**/*.pb.*,**/mk-include/**/*,**/test/**/*,**/tests/**/*,**/*Test.java
sonar.language=java
sonar.projectKey=common-docker
sonar.sources=.
sonar.java.binaries=target-AMD/**/classes,target-ARM/**/classes
sonar.coverage.jacoco.xmlReportPaths=target-AMD/**/jacoco.xml,target-ARM/**/jacoco.xml
