# Copyright 2021 Jack Viers

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM docker.io/openjdk:11.0.13-slim-bullseye

ARG VERSION
ARG ARCH
ARG PYTHON_CONFLUENT_DOCKER_UTILS_INSTALL_SPEC="git+https://github.com/confluentinc/confluent-docker-utils@v0.0.49"

LABEL version=$VERSION
LABEL name="cp-base"
LABEL summary="Common base image for Confluent Components' Docker images."

ENV LANG="C.UTF-8"
ENV CUB_CLASSPATH='"/usr/share/java/cp-base-new/*"'
ENV DEBIAN_FRONTEND=noninteractive
ENV LIBSODIUM_MAKE_ARGS="-j 2"

RUN apt update \
	&& apt install -y \
	build-essential \
	wget \
	nmap \
	ncat \
	python3 \
	procps \
	krb5-user \
	iputils-tracepath \
	iputils-ping \
	iputils-clockdiff \
	iputils-arping \
	python3-pip \
	git \
	&& update-alternatives --install /usr/bin/python python /usr/bin/python3 99 \
	&& python3 -m pip install --upgrade "pip>=21,<22" \
	&& python3 -m pip install --prefer-binary --prefix=/usr/local --upgrade ${PYTHON_CONFLUENT_DOCKER_UTILS_INSTALL_SPEC} \
	&& apt remove -y git \
	&& apt clean \
	&& rm -rf /tmp/* \
	&& mkdir -p /etc/confluent/docker /usr/logs/ \
	&& useradd --no-log-init --create-home --shell /bin/bash appuser \
	&& chown appuser:appuser -R /etc/confluent/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/net/sourceforge/argparse4j/argparse4j/0.7.0/argparse4j-0.7.0.jar \
	https://repo1.maven.org/maven2/org/apache/yetus/audience-annotations/0.5.0/audience-annotations-0.5.0.jar \
	https://packages.confluent.io/maven/io/confluent/common-utils/7.0.0/common-utils-7.0.0.jar \
	https://repo1.maven.org/maven2/commons-cli/commons-cli/1.4/commons-cli-1.4.jar \
	https://repo1.maven.org/maven2/io/confluent/confluent-log4j/1.2.17-cp2/confluent-log4j-1.2.17-cp2.jar \
	https://packages.confluent.io/maven/io/confluent/disk-usage-agent/7.0.0/disk-usage-agent-7.0.0.jar \
	https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.6/gson-2.8.6.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.12.3/jackson-dataformat-csv-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.12.3/jackson-dataformat-yaml-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.12.3/jackson-datatype-jdk8-2.12.3.jar \
	https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.12.3/jackson-module-scala_2.13-2.12.3.jar \
	https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.14.0/jmx_prometheus_javaagent-0.14.0.jar \
	https://repo1.maven.org/maven2/org/jolokia/jolokia-core/1.6.2/jolokia-core-1.6.2.jar \
	https://repo1.maven.org/maven2/org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar \
	https://repo1.maven.org/maven2/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar \
	https://repo1.maven.org/maven2/com/googlecode/json-simple/json-simple/1.1.1/json-simple-1.1.1.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/7.0.0-ccs/kafka-clients-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-metadata/7.0.0-ccs/kafka-metadata-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-raft/7.0.0-ccs/kafka-raft-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-server-common/7.0.0-ccs/kafka-server-common-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-storage/7.0.0-ccs/kafka-storage-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka-storage-api/7.0.0-ccs/kafka-storage-api-7.0.0-ccs.jar \
	https://packages.confluent.io/maven/org/apache/kafka/kafka_2.13/7.0.0-ccs/kafka_2.13-7.0.0-ccs.jar \
	https://repo1.maven.org/maven2/org/lz4/lz4-java/1.7.1/lz4-java-1.7.1.jar \
	https://repo1.maven.org/maven2/com/yammer/metrics/metrics-core/2.2.0/metrics-core-2.2.0.jar \
	https://repo1.maven.org/maven2/io/dropwizard/metrics/metrics-core/4.1.12.1/metrics-core-4.1.12.1.jar \
	https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar \
	https://repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.13/2.4.4/scala-collection-compat_2.13-2.4.4.jar \
	https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.13/1.0.0/scala-java8-compat_2.13-1.0.0.jar \
	https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.5/scala-library-2.13.5.jar \
	https://repo1.maven.org/maven2/com/typesafe/scala-logging/scala-logging_2.13/3.9.3/scala-logging_2.13-3.9.3.jar \
	https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.5/scala-reflect-2.13.5.jar \
	https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar \
	https://repo1.maven.org/maven2/org/slf4j/slf4j-simple/1.7.30/slf4j-simple-1.7.30.jar \
	https://repo1.maven.org/maven2/org/yaml/snakeyaml/1.27/snakeyaml-1.27.jar \
	https://repo1.maven.org/maven2/org/xerial/snappy/snappy-java/1.1.8.1/snappy-java-1.1.8.1.jar \
	https://packages.confluent.io/maven/io/confluent/utility-belt/7.0.0/utility-belt-7.0.0.jar \
	https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.6.3/zookeeper-3.6.3.jar \
	https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper-jute/3.6.3/zookeeper-jute-3.6.3.jar /usr/share/java/cp-base-new/

ADD --chown=appuser:appuser https://repo1.maven.org/maven2/com/github/luben/zstd-jni/1.5.0-2/zstd-jni-1.5.0-2-linux_arm.jar /usr/share/java/cp-base-new/zstd-jni-1.5.0-2.jar

COPY --chown=appuser:appuser include/etc/confluent/docker /etc/confluent/docker

USER appuser
WORKDIR /home/appuser

CMD ["echo" "built!"]
